import numpy as np
import matplotlib.pyplot as plt
import pylab
import pandas as pd
import Tkinter,tkFileDialog

root = Tkinter.Tk()
filez = tkFileDialog.askopenfilenames(parent=root,title='Choose 2 or more files',filetypes=(("csv files","*csv"),("All files","*.*" )))
t=list(filez)
p=len(filez)
root.destroy()

if p==1:
    data0 = pd.read_csv(t[0],sep=u',', header=14, skip_footer=0)
    plt.plot(data0) 
if p==2:
    data0 = pd.read_csv(t[0],sep=u',', header=14, skip_footer=0)
    data1 = pd.read_csv(t[1],sep=u',', header=14, skip_footer=0)
    plt.plot(data0) 
    plt.plot(data1)
if p==3:
    data0 = pd.read_csv(t[0],sep=u',', header=14, skip_footer=0)
    data1 = pd.read_csv(t[1],sep=u',', header=14, skip_footer=0)
    data2 = pd.read_csv(t[2],sep=u',', header=14, skip_footer=0)
    plt.plot(data0) 
    plt.plot(data1) 
    plt.plot(data2) 
if p==4:
    data0 = pd.read_csv(t[0],sep=u',', header=14, skip_footer=0)
    data1 = pd.read_csv(t[1],sep=u',', header=14, skip_footer=0)
    data2 = pd.read_csv(t[2],sep=u',', header=14, skip_footer=0)
    data3 = pd.read_csv(t[3],sep=u',', header=14, skip_footer=0)
    plt.plot(data0) 
    plt.plot(data1) 
    plt.plot(data2) 
    plt.plot(data3)
if p==5:
    data0 = pd.read_csv(t[0],sep=u',', header=14, skip_footer=0)
    data1 = pd.read_csv(t[1],sep=u',', header=14, skip_footer=0)
    data2 = pd.read_csv(t[2],sep=u',', header=14, skip_footer=0)
    data3 = pd.read_csv(t[3],sep=u',', header=14, skip_footer=0)
    data4 = pd.read_csv(t[4],sep=u',', header=14, skip_footer=0)
    plt.plot(data0) 
    plt.plot(data1) 
    plt.plot(data2) 
    plt.plot(data3) 
    plt.plot(data4) 
if p==6:
    data0 = pd.read_csv(t[0],sep=u',', header=14, skip_footer=0)
    data1 = pd.read_csv(t[1],sep=u',', header=14, skip_footer=0)
    data2 = pd.read_csv(t[2],sep=u',', header=14, skip_footer=0)
    data3 = pd.read_csv(t[3],sep=u',', header=14, skip_footer=0)
    data4 = pd.read_csv(t[4],sep=u',', header=14, skip_footer=0)
    data5 = pd.read_csv(t[5],sep=u',', header=14, skip_footer=0)
    plt.plot(data0) 
    plt.plot(data1) 
    plt.plot(data2) 
    plt.plot(data3) 
    plt.plot(data4) 
    plt.plot(data5)
if p==7:
    data0 = pd.read_csv(t[0],sep=u',', header=14, skip_footer=0)
    data1 = pd.read_csv(t[1],sep=u',', header=14, skip_footer=0)
    data2 = pd.read_csv(t[2],sep=u',', header=14, skip_footer=0)
    data3 = pd.read_csv(t[3],sep=u',', header=14, skip_footer=0)
    data4 = pd.read_csv(t[4],sep=u',', header=14, skip_footer=0)
    data5 = pd.read_csv(t[5],sep=u',', header=14, skip_footer=0)
    data6 = pd.read_csv(t[6],sep=u',', header=14, skip_footer=0)
    plt.plot(data0) 
    plt.plot(data1) 
    plt.plot(data2) 
    plt.plot(data3) 
    plt.plot(data4) 
    plt.plot(data5)
    plt.plot(data6)
if p==8:
    data0 = pd.read_csv(t[0],sep=u',', header=14, skip_footer=0)
    data1 = pd.read_csv(t[1],sep=u',', header=14, skip_footer=0)
    data2 = pd.read_csv(t[2],sep=u',', header=14, skip_footer=0)
    data3 = pd.read_csv(t[3],sep=u',', header=14, skip_footer=0)
    data4 = pd.read_csv(t[4],sep=u',', header=14, skip_footer=0)
    data5 = pd.read_csv(t[5],sep=u',', header=14, skip_footer=0)
    data6 = pd.read_csv(t[6],sep=u',', header=14, skip_footer=0)
    data7 = pd.read_csv(t[7],sep=u',', header=14, skip_footer=0)   
    plt.plot(data0) 
    plt.plot(data1) 
    plt.plot(data2) 
    plt.plot(data3) 
    plt.plot(data4) 
    plt.plot(data5)
    plt.plot(data6)
    plt.plot(data7)

plt.show()
